<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Error de validacion en el formular_4358bd</name>
   <tag></tag>
   <elementGuidId>f77713ca-54bb-48b4-a001-5e367eb30cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='form-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ff340aeb-4e88-48ab-83db-515fa248283f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-contact-txt-msg input-lg form-full</value>
      <webElementGuid>bfe149b3-c8e1-4951-91e5-16d1eb4b5589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-message</value>
      <webElementGuid>fd2c0bdd-185a-40e2-89bc-8513fbd8c60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>286fb001-e7d0-4172-bd44-79bc2b38f062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>a400af14-35c4-4f44-85f2-c2ac8123e29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mensaje</value>
      <webElementGuid>8987ea69-384e-44a4-8f69-41285ffe81e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a2a8d2e-b040-4acf-b205-e2c24640ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-message&quot;)</value>
      <webElementGuid>154961ba-2c7a-4def-b821-de1a126114df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='form-message']</value>
      <webElementGuid>3bd5ae31-ce01-48c2-b995-46545dda3f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact']/div[6]/div/textarea</value>
      <webElementGuid>233b9bda-6d6a-4673-91ea-c364b9335cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d6cdc3a8-0efd-434c-9466-54853120b6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'form-message' and @name = 'Message' and @placeholder = 'Mensaje']</value>
      <webElementGuid>0132b5cf-0a2e-4676-986f-a68e01121e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
