<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Data_Interno</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e8e9189c-7f83-462c-8be9-66221e93b60b</testSuiteGuid>
   <testCaseLink>
      <guid>48d12fad-91e4-46e4-96b0-16cc744e74ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Datos_Excel/Caso_Datos_Excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2e7ed347-16fc-42b2-a416-ad3f3c2bfcc0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Excel/Data_interno</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2e7ed347-16fc-42b2-a416-ad3f3c2bfcc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>a845afb6-ef47-4c9b-a829-09715d4ad4d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e7ed347-16fc-42b2-a416-ad3f3c2bfcc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>0a636370-d808-45f0-aff8-ac8bda33c0ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e7ed347-16fc-42b2-a416-ad3f3c2bfcc0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>26649f60-1490-4ab7-bbf5-8240a1ac3ffb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
