<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Data_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bf1e9746-5ef3-45dd-b4f8-b1722c53010b</testSuiteGuid>
   <testCaseLink>
      <guid>ea226387-5c0f-48d3-8d8c-139590570352</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Datos_Excel/Caso_Datos_Excel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ffa1de84-3cfb-4b0b-b3ba-27d1eeecd1d8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Excel/Base_excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ffa1de84-3cfb-4b0b-b3ba-27d1eeecd1d8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombre</value>
         <variableId>a845afb6-ef47-4c9b-a829-09715d4ad4d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ffa1de84-3cfb-4b0b-b3ba-27d1eeecd1d8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>apellido</value>
         <variableId>0a636370-d808-45f0-aff8-ac8bda33c0ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ffa1de84-3cfb-4b0b-b3ba-27d1eeecd1d8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>26649f60-1490-4ab7-bbf5-8240a1ac3ffb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
