<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What type is it_filetype</name>
   <tag></tag>
   <elementGuidId>bb0dec88-8016-4c40-8cdf-d9270c8d8faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itsanimage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsanimage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49e9da78-51d2-4a1d-883a-7f5c2715d06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4e6a14b3-6fdd-4d2d-a9aa-28cb92cca0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsanimage</value>
      <webElementGuid>6bccfc5e-5419-4fb0-bf6a-e9d631027dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filetype</value>
      <webElementGuid>1882f5d2-8192-4f78-9f93-a92d39ac19cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5d4667ed-3f30-4446-910b-01fdf0669b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsanimage&quot;)</value>
      <webElementGuid>23e83a43-91fa-41f5-95bb-3c008ac07c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsanimage']</value>
      <webElementGuid>7584ffe4-2a6e-4a70-b1e6-335a7c4331b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e77e2ebf-946e-4c61-ac6b-ea2c135bfdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'itsanimage' and @name = 'filetype']</value>
      <webElementGuid>41a5b13c-73b4-4d5b-8342-9abd8cc7ee16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
