<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calculateButton</name>
   <tag></tag>
   <elementGuidId>ce4cca6a-db09-4859-89d8-f42f2a34af57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculateButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calculateButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d881e9f-5e6b-42cb-9a49-8d23f97bedb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b99f745b-0aed-475d-b276-c14d348b3524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1b632f59-da73-43bf-bdb8-ba6343b57f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculateButton</value>
      <webElementGuid>dfdb8dc6-2087-4ffb-9a67-697f520ee722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>ca5e72a0-ccd2-429e-b883-f003f16ca414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calculate()</value>
      <webElementGuid>5fe59ec5-ca9f-4cf7-9d52-5801c5535210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculateButton&quot;)</value>
      <webElementGuid>d199fd87-d861-40b0-a792-559858ee1542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calculateButton']</value>
      <webElementGuid>55c9cb8a-19a1-4437-810e-5fc31c5f1301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[4]/div[2]/input</value>
      <webElementGuid>dde5e935-b846-4f67-b4b6-252fd1694f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>19fb93da-449a-40a5-b5bb-998c0c455322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'calculateButton']</value>
      <webElementGuid>7bbf2454-8db5-403a-ac56-aab34d254447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
