<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>combo</name>
   <tag></tag>
   <elementGuidId>10795c89-2894-45bb-ba56-06c34e1c2da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOperationDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOperationDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edc166e5-e437-4fdd-b751-e227b968e85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>251ce67f-a319-45c8-bc50-51070cdd28a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOperationDropdown</value>
      <webElementGuid>c785399f-a11e-4cab-b164-974e735a1498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectOperation</value>
      <webElementGuid>d01171b6-bc9f-4de7-8515-19020c284585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>operationChanged(this.preset)</value>
      <webElementGuid>3a25cb4f-2932-4416-972d-8cbeb863dc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        </value>
      <webElementGuid>23eb8eda-d207-470f-8aec-90d432e9ead3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOperationDropdown&quot;)</value>
      <webElementGuid>c7a36f0a-460a-49a3-b2de-c87a267c175f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOperationDropdown']</value>
      <webElementGuid>4bbd7442-01cd-4cf3-a2c2-0bc44b4af7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[3]/div[2]/select</value>
      <webElementGuid>d4a38a10-3f60-41fb-a87a-3e8bea2f62fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::select[1]</value>
      <webElementGuid>b8cb9828-3a8c-46c6-9926-136474886b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second number'])[1]/following::select[1]</value>
      <webElementGuid>ce75c5cb-1c28-4e78-ba4b-f2c31e896a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculating ...'])[1]/preceding::select[1]</value>
      <webElementGuid>4065db93-bcaf-43be-a65e-706bf7b2af75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer'])[1]/preceding::select[1]</value>
      <webElementGuid>66145844-9b65-4387-ac15-005a72116dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>2b5b5542-1485-4ff5-9824-eaf7ba8a1763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOperationDropdown' and @name = 'selectOperation' and (text() = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ' or . = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ')]</value>
      <webElementGuid>80dfcabf-e7f8-4ef9-b048-4cf7f4ac4a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
