<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>number1</name>
   <tag></tag>
   <elementGuidId>041047c5-75ea-4d10-9e9e-74d86a918a65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number1Field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number1Field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f989636f-c65f-4d0c-b301-f79f45420516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number1Field</value>
      <webElementGuid>2101d1c7-524b-4716-8d27-bbe081a0c6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number1</value>
      <webElementGuid>c4001ef3-5e18-48cc-95a7-031e7997a43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>358854bf-4a80-4d97-b2ed-2b0fcf80a54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1308af53-f139-474d-a6ae-5537c85ee0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4a41037f-07f9-46eb-9de3-3da26fa0e3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number1Field&quot;)</value>
      <webElementGuid>f6301a9e-51f7-4893-8f7f-a08f03d0b8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number1Field']</value>
      <webElementGuid>35e93992-76df-4b73-bbe6-46356147b091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div/div[2]/input</value>
      <webElementGuid>9fe1c248-e375-4065-ad3c-dd09f8b6d14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>873fc435-a812-4f28-86fc-3793424bfff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number1Field' and @name = 'number1' and @type = 'text']</value>
      <webElementGuid>c00a017d-7d90-45d0-8598-5b41cc911fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
