<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultado</name>
   <tag></tag>
   <elementGuidId>d71c4730-96aa-4618-9474-fc33f18435e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberAnswerField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberAnswerField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ede58ecf-f4db-4042-83fc-037b2aea541d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberAnswerField</value>
      <webElementGuid>f4a1a5a5-cdd5-4a63-84b3-bdb0b4ae35e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberAnswer</value>
      <webElementGuid>711066ff-91f5-4699-8dc8-6c7682894e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>7463a9f1-cda3-47ce-974c-8c1bf0e50e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1456b001-8abc-4833-a1ae-ace4228b9cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>032bf292-434a-472a-9256-b0b38c965530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberAnswerField&quot;)</value>
      <webElementGuid>fd251867-e69e-45c5-9837-7d8599d02de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberAnswerField']</value>
      <webElementGuid>90c1f939-380b-4ecc-8c8b-2fd0be6c06dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='answerForm']/div/div[2]/input</value>
      <webElementGuid>7def2b09-a5db-49af-b1e7-7ffc1abbbc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[4]/div/div[2]/input</value>
      <webElementGuid>d49360a7-3fd1-468e-897f-a70d5b1c1481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'numberAnswerField' and @name = 'numberAnswer' and @type = 'text']</value>
      <webElementGuid>b771d1c9-218b-4625-9852-000e51a2cd4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
