<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Slower      Slow      Medium      Fa_f36099</name>
   <tag></tag>
   <elementGuidId>c2781add-9d4e-49ad-aafa-8bebfaefb4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='speed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#speed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d28ece9f-2811-48c8-a527-3d1eae5fe2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>speed</value>
      <webElementGuid>874218cf-96df-4316-83fd-fe266bce97b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speed</value>
      <webElementGuid>0cfff127-1db5-4659-a3a7-41d13a2d13c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Slower
      Slow
      Medium
      Fast
      Faster
    </value>
      <webElementGuid>aa627ef4-892a-40c6-8974-7c1466c5b0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speed&quot;)</value>
      <webElementGuid>4722eb5f-0f12-4ffc-b80e-8603e2e15a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='speed']</value>
      <webElementGuid>56f2796d-0b0a-4b69-ac10-c6ef1c723128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML6']/div/form/fieldset/select</value>
      <webElementGuid>880325dc-8b69-4bbe-9b08-5ec889764297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a speed'])[1]/following::select[1]</value>
      <webElementGuid>0e68ff6e-f413-4d95-889a-9fac298d6dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select menu'])[1]/following::select[1]</value>
      <webElementGuid>4cac0cb0-3f61-4f2c-9042-e47227f3f2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a file'])[1]/preceding::select[1]</value>
      <webElementGuid>91e0bc9b-19a0-4e46-a1ca-a643cdecb64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a number'])[1]/preceding::select[2]</value>
      <webElementGuid>de819d12-0f44-42d7-af58-0ec7577515ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>80c277f9-d7c3-418e-a8eb-9c1290041440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'speed' and @id = 'speed' and (text() = '
      Slower
      Slow
      Medium
      Fast
      Faster
    ' or . = '
      Slower
      Slow
      Medium
      Fast
      Faster
    ')]</value>
      <webElementGuid>5be5412e-8bb0-43a4-9ae3-8b20625633b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
