<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTACTO</name>
   <tag></tag>
   <elementGuidId>c07cf573-8460-46b0-8d7c-b098d9bf6f00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div[3]/ul[2]/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a.external</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5415616b-ef20-4227-b4bf-ded2cca7e62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>external</value>
      <webElementGuid>91cd7ab3-d6d3-41cb-bc29-7998116234c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Contacto</value>
      <webElementGuid>9ccd3cf3-9a39-4ef4-b26b-8e707e4843f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTACTO</value>
      <webElementGuid>a1c4f315-5420-494b-9417-27d865578cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;nav-menu singlepage-nav&quot;]/ul[@class=&quot;nav-menu-inner&quot;]/li[9]/a[@class=&quot;external&quot;]</value>
      <webElementGuid>e3e5993c-556d-4f39-890b-ddc0600f24bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div[3]/ul[2]/li[9]/a</value>
      <webElementGuid>5e428f96-7cb7-44a1-9726-75d598987a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTACTO')]</value>
      <webElementGuid>cb498271-2bfb-4964-8cb6-04aeb6ef5f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRABAJAR EN BALIARDA'])[1]/following::a[1]</value>
      <webElementGuid>e1bbf6fa-c2fa-41e0-8ac4-73e42fe0d2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WEB-MEDIOS'])[1]/following::a[2]</value>
      <webElementGuid>dfc00ac1-cb40-4c47-93be-ed4709efd751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bienvenidos'])[1]/preceding::a[2]</value>
      <webElementGuid>7c05a910-0594-4298-8e12-38e42eec769a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quiénes Somos'])[1]/preceding::a[2]</value>
      <webElementGuid>fd917c3e-ad91-4280-b844-08f2fb712624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTACTO']/parent::*</value>
      <webElementGuid>74dfe8ee-41cd-4514-add7-310965feac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Contacto')]</value>
      <webElementGuid>fed9bc56-6f35-452a-a942-085ca4aa5242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>535f87ec-5e84-42c5-a27a-962799075cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Contacto' and (text() = 'CONTACTO' or . = 'CONTACTO')]</value>
      <webElementGuid>f81d8c75-c821-4ac0-92d6-d4fac7d59b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
