<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>07fa047b-9650-4313-b151-6044cee06b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d14230a-d298-4f50-baad-bb4f78a5b177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/image/cache/catalog/demo/macbook_2-74x74.jpg</value>
      <webElementGuid>46787b12-4248-41a9-aade-70602f0491d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>d5e9987d-060b-4883-bbcf-8d83372118e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>cbddd1fe-7a36-4426-9a90-f61882ce0bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pagespeed-url-hash</name>
      <type>Main</type>
      <value>1164130264</value>
      <webElementGuid>fb734d8f-36a8-4153-91a2-8f9cdcf11658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>pagespeed.CriticalImages.checkImageForCriticality(this);</value>
      <webElementGuid>d6a9ad3b-4fe6-4838-a7e7-1c4b77bc229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/ul[@class=&quot;thumbnails&quot;]/li[@class=&quot;image-additional&quot;]/a[@class=&quot;thumbnail&quot;]/img[1]</value>
      <webElementGuid>29ce8497-bd6d-4da7-9759-9d94413eff5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/ul/li[4]/a/img</value>
      <webElementGuid>264feb64-e634-4715-aea3-05ba18ef3bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='MacBook'])[4]</value>
      <webElementGuid>d2068294-9ba2-4896-af7d-23b1b28cc3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>980f4150-fb68-47e1-970d-d41aa88f9e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://opencart.abstracta.us:80/image/cache/catalog/demo/macbook_2-74x74.jpg' and @title = 'MacBook' and @alt = 'MacBook']</value>
      <webElementGuid>fe40d0f3-c282-4ddf-b6b3-3471697bb00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
