<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Automation Testing Practice_frame-on_f39fe2</name>
   <tag></tag>
   <elementGuidId>355188c0-3c0d-468a-8946-b0f465d044ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame-one1434677811']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame-one1434677811</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9f6e5e7b-3c83-4e15-bee2-a5a6ace5d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04fe20ba-2aac-4c84-8712-f6cea5519e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-one1434677811</value>
      <webElementGuid>0129f3f0-d33a-4581-bf49-2b36c563e47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ab55c2fc-a377-441c-ac5d-cc20a87c546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fs2.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTBHmkDZCZ6tSK_3bsAv-gQi&amp;1434677811&amp;EmbedId=1434677811</value>
      <webElementGuid>68b6aa7b-d2b9-48af-b8a3-3eaa39eade1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1469</value>
      <webElementGuid>49582696-6fe3-492c-90b8-5dfd3340bb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-one1434677811&quot;)</value>
      <webElementGuid>a4b7335c-83bd-4340-a43b-b8c4eb1dae04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame-one1434677811']</value>
      <webElementGuid>bbc06321-7195-4b03-aeaa-52e8118ec536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-1307673142697428135']/iframe</value>
      <webElementGuid>64b4dfbd-c03b-4e41-9cc1-b8fb268c9e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>26f4fff0-b8fc-4e40-ac54-22f3ef67fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'frame-one1434677811' and @src = 'https://fs2.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTBHmkDZCZ6tSK_3bsAv-gQi&amp;1434677811&amp;EmbedId=1434677811']</value>
      <webElementGuid>cd13e854-3a99-4c1a-b6c3-9f0b4a21257e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
