<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Salary_salary</name>
   <tag></tag>
   <elementGuidId>8a26d298-0e52-4376-95b8-f4ccddf72bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#salary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='salary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57549287-b0c4-4a6e-9b86-f68147fe7c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b586999-c18b-4630-86b5-38dd02e1a6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>d0d7e4ed-1a8c-47a8-929f-ae8cc9eee808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d96a6928-fa87-4af8-ae79-c5bbccd8212d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>20695e12-a547-47a8-976b-02f5b55149fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Salary</value>
      <webElementGuid>2983929e-d724-4f7c-85f5-ef8713204f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68936d5a-0e47-4f17-88e0-bed835b5a1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>salary</value>
      <webElementGuid>1db3be65-6793-453d-81cc-1511749c77a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> mr-sm-2 form-control</value>
      <webElementGuid>dc32b97d-6925-48a7-b669-05c21f8dcd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>25a02ed7-2ce6-47c2-8d76-319a5b1b71bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;salary&quot;)</value>
      <webElementGuid>26198670-3f77-46f9-8ba9-d0e75965a320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='salary']</value>
      <webElementGuid>13bf7897-b40c-4dd5-acfc-5fc0ba843e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='salary-wrapper']/div[2]/input</value>
      <webElementGuid>b805235a-f64e-4b30-8e3e-96185f0a3162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>875d7727-76db-4017-a1ba-846ba1103d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Salary' and @type = 'text' and @id = 'salary']</value>
      <webElementGuid>b8361ed1-8b19-4012-931c-6a2b6eafce19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
